require_relative "base/collection"

module XMLDBApi
  class RedCollection < XMLDBApi::Base::Collection
    
      # Returns the name associated with the Collection instance.
      # ==== Return value
      # String representing the name of the collection
      def get_name()
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end

      # Provides a Array of all services known to the collection. If no services
      # are known an empty Array is returned.
      # ==== Return value
      # An array of registered Service implementations.
      # ==== Raises
      # XMLDBApi::Base::XMLDBException with expected error codes.
      # ErrorCodes.COLLECTION_CLOSED if the close
      # method has been called on the RedCollection
      def get_services()
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end

      # Returns a Service instance for the requested service name and version. If
      # o Service exists for those parameters a nil value is returned.
      # ==== Parameters
      # * +name+ - Name of the service to be retrieved
      # * +version+ - Version of the service to be retrieved
      # ==== Return value
      # An array of registered Service implementations.
      # ==== Raises
      # XMLDBApi::Base::XMLDBException with expected error codes.
      # ErrorCodes.COLLECTION_CLOSED if the close
      # method has been called on the RedCollection
      def get_service(name, version)
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end

      # Returns the parent collection for this collection or nil if no parent
      # collection exists.
      # ==== Return value
      # XMLDBApi::RedCollection instance or nil
      # ==== Raises
      # XMLDBApi::Base::XMLDBException with expected error codes.
      # ErrorCodes.COLLECTION_CLOSED if the close
      # method has been called on the RedCollection
      def get_parent_collection
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end

      # Returns the number of child collections under this
      # Collection or 0 if no child collections exist.
      # ==== Return value
      # The number of child collections
      # ==== Raises
      # XMLDBApi::Base::XMLDBException with expected error codes.
      # ErrorCodes.COLLECTION_CLOSED if the close
      # method has been called on the RedCollection
      def get_child_collection_count()
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end

      # Returns a list of collection names naming all child collections
      # of the current collection. If no child collections exist an empty list is
      # returned.
      # ==== Return value
      # Array containing collection names for all child collections.
      # ==== Raises
      # XMLDBApi::Base::XMLDBException with expected error codes.
      # ErrorCodes.COLLECTION_CLOSED if the close
      # method has been called on the RedCollection
      def list_child_collections()
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end

      # Returns XMLDBApi::RedCollection instance for the requested child collection
      # if it exists.
      # ==== Parameters
      # * +name+ - Name of the child collection to retrieve
      # ==== Return value
      # The requested child collection or null if it couldn't be found.
      # ==== Raises
      # XMLDBApi::Base::XMLDBException with expected error codes.
      # ErrorCodes.COLLECTION_CLOSED if the close
      # method has been called on the RedCollection
      def get_child_collection(name)
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end

      # Returns the number of resources currently stored in this collection or 0
      # if the collection is empty.
      # ==== Return value
      # The number of resource in the collection.
      # ==== Raises
      # XMLDBApi::Base::XMLDBException with expected error codes.
      # ErrorCodes.COLLECTION_CLOSED if the close
      # method has been called on the RedCollection
      def get_resource_count()
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end

      # Returns a list of the ids for all resources stored in the collection.
      # ==== Return value
      # String Array containing the names for all Resources in the collection.
      # ==== Raises
      # XMLDBApi::Base::XMLDBException with expected error codes.
      # ErrorCodes.COLLECTION_CLOSED if the close
      # method has been called on the RedCollection
      def list_resources()
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end
      
      # Creates a new empty Resource with the provided id.
      # The type of Resource returned is determined by the type
      # parameter. Only RedXMLResource is supported.
      # The id provided must be unique within the scope of the
      # collection. If id is nil or its value is empty then an id 
      # is generated by calling createId. The Resource created is not 
      # stored to the database until storeResource is called.
      # ==== Parameters
      # * +id+ - The unique id to associate with the created RedXMLResource
      # * +type+ - The Resource type to create
      # ==== Return value
      # An empty RedXMLResource instance
      # ==== Raises
      # XMLDBApi::Base::XMLDBException with expected error codes.
      # ErrorCodes.UNKNOWN_RESOURCE_TYPE if the type
      # parameter is not a known Resource type.
      # ErrorCodes.COLLECTION_CLOSED if the close
      # method has been called on the RedCollection
      def create_resource(s_id, type)
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end

      # Removes the RedXMLResource from the database.
      # ==== Parameters
      # * +res+ - The RedXMLResource to remove
      # ==== Raises
      # XMLDBApi::Base::XMLDBException with expected error codes.
      # ErrorCodes.INVALID_RESOURCE if the Resource is not valid.
      # ErrorCodes.NO_SUCH_RESOURCE if the Resource is not known 
      # to this Collection
      # ErrorCodes.COLLECTION_CLOSED if the close
      # method has been called on the RedCollection
      def removeResource(res)
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end

      # Stores the provided RedXMLResource into the database. If the resource does not
      # already exist it will be created. If it does already exist it will be
      # updated.
      # ==== Parameters
      # * +res+ - The RedXMLResource to store in the database
      # ==== Raises
      # XMLDBApi::Base::XMLDBException with expected error codes.
      # ErrorCodes.INVALID_RESOURCE if the Resource is not valid.
      # ErrorCodes.COLLECTION_CLOSED if the close
      # method has been called on the RedCollection
      def store_resource(res)
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end

      # Retrieves a RedXMLResource from the database. If the RedXMLResource
      # could not be located a nil value will be returned.
      # ==== Parameters
      # * +id+ - The Unique id for the requested resource
      # ==== Return value
      # The retrieved RedXMLResource instance
      # ==== Raises
      # XMLDBApi::Base::XMLDBException with expected error codes.
      # ErrorCodes.COLLECTION_CLOSED if the close
      # method has been called on the RedCollection
      def get_resource(s_id)
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end
      
      # Creates a new unique ID within the context of the RedCollection
      # ==== Return value
      # The created ID as a String
      # ==== Raises
      # XMLDBApi::Base::XMLDBException with expected error codes.
      # ErrorCodes.COLLECTION_CLOSED if the close
      # method has been called on the RedCollection
      def create_id()
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end

      # Returns true if the RedCollection is open false otherwise.
      # Calling the close method on RedCollection will result in is_open?
      # returning false. It is not safe to use RedCollection instances
      # that have been closed.
      # ==== Return value
      # True if the RedCollection is open, false otherwise.
      def is_open?()
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end
      
      # Releases all resources consumed by the Collection.
      # The close method must always be called when use of
      # a RedCollection is complete. It is not safe to use a\
      # RedCollection after the close method has been called.
      def close()
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end
      
      # Returns the value of the property identified by name parameter
      # ==== Parameters
      # * +name+ - The name of the property to retrieve
      # ==== Return value
      # The property value or null if no property exists.
      def get_property(name)
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end

      # Sets the property name to have the value provided in value
      # ==== Parameters
      # * +name+ - The name of the property to set
      # * +value+ - The value to set for the property
      def set_property(name, value)
        raise XMLDBApi::Base::ErrorCodes::NotImplemetedError
      end
  end
end